### ISSUE TITLE
Building Prometheus plugin fails

### ISSUE THREAD

**Issue by SquupS** [headlamp-k8s/plugins#31]
Hi,

I tried building the prometheus plugin in order to ship it to my in-cluster deployment of headlamp but unfortunately the build of the plugin is failing with the following error.  Any help would be appreciated!

`Errors:

ModuleNotFoundError: Module not found: Error: Can't resolve 'use-between' in '/headlamp-plugins/prometheus/src'
    at /root/.npm/_npx/03f1d306e9548fcf/node_modules/webpack/lib/Compilation.js:2029:28
    at /root/.npm/_npx/03f1d306e9548fcf/node_modules/webpack/lib/NormalModuleFactory.js:895:13
    at eval (eval at create (/root/.npm/_npx/03f1d306e9548fcf/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /root/.npm/_npx/03f1d306e9548fcf/node_modules/webpack/lib/NormalModuleFactory.js:332:22
    at eval (eval at create (/root/.npm/_npx/03f1d306e9548fcf/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /root/.npm/_npx/03f1d306e9548fcf/node_modules/webpack/lib/NormalModuleFactory.js:509:22
    at /root/.npm/_npx/03f1d306e9548fcf/node_modules/webpack/lib/NormalModuleFactory.js:151:11
    at /root/.npm/_npx/03f1d306e9548fcf/node_modules/webpack/lib/NormalModuleFactory.js:767:25
    at /root/.npm/_npx/03f1d306e9548fcf/node_modules/webpack/lib/NormalModuleFactory.js:979:8
    at /root/.npm/_npx/03f1d306e9548fcf/node_modules/webpack/lib/NormalModuleFactory.js:1109:5
    at /root/.npm/_npx/03f1d306e9548fcf/node_modules/neo-async/async.js:6883:13
    at /root/.npm/_npx/03f1d306e9548fcf/node_modules/webpack/lib/NormalModuleFactory.js:1092:45
    at finishWithoutResolve (/root/.npm/_npx/03f1d306e9548fcf/node_modules/enhanced-resolve/lib/Resolver.js:567:11)
    at /root/.npm/_npx/03f1d306e9548fcf/node_modules/enhanced-resolve/lib/Resolver.js:656:15
    at /root/.npm/_npx/03f1d306e9548fcf/node_modules/enhanced-resolve/lib/Resolver.js:714:5
    at eval (eval at create (/root/.npm/_npx/03f1d306e9548fcf/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /root/.npm/_npx/03f1d306e9548fcf/node_modules/enhanced-resolve/lib/Resolver.js:714:5
    at eval (eval at create (/root/.npm/_npx/03f1d306e9548fcf/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /root/.npm/_npx/03f1d306e9548fcf/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:89:43
    at /root/.npm/_npx/03f1d306e9548fcf/node_modules/enhanced-resolve/lib/Resolver.js:714:5
    at eval (eval at create (/root/.npm/_npx/03f1d306e9548fcf/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /root/.npm/_npx/03f1d306e9548fcf/node_modules/enhanced-resolve/lib/Resolver.js:714:5
    at eval (eval at create (/root/.npm/_npx/03f1d306e9548fcf/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /root/.npm/_npx/03f1d306e9548fcf/node_modules/enhanced-resolve/lib/Resolver.js:714:5
    at eval (eval at create (/root/.npm/_npx/03f1d306e9548fcf/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /root/.npm/_npx/03f1d306e9548fcf/node_modules/enhanced-resolve/lib/Resolver.js:714:5
    at eval (eval at create (/root/.npm/_npx/03f1d306e9548fcf/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /root/.npm/_npx/03f1d306e9548fcf/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:89:43
    at /root/.npm/_npx/03f1d306e9548fcf/node_modules/enhanced-resolve/lib/Resolver.js:714:5
    at eval (eval at create (/root/.npm/_npx/03f1d306e9548fcf/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /root/.npm/_npx/03f1d306e9548fcf/node_modules/enhanced-resolve/lib/Resolver.js:714:5
    at eval (eval at create (/root/.npm/_npx/03f1d306e9548fcf/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /root/.npm/_npx/03f1d306e9548fcf/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:41:15
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
resolve 'use-between' in '/headlamp-plugins/prometheus/src'
  Parsed request is a module
  using description file: /headlamp-plugins/prometheus/package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /headlamp-plugins/prometheus/src/node_modules doesn't exist or is not a directory
      /headlamp-plugins/prometheus/node_modules doesn't exist or is not a directory
      /headlamp-plugins/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory`

**Comment by SquupS** [comment]
Fixed it. Need to add "RUN npm install" after the COPY step in the docker file since building it via Azure Pipelines or local
