### ISSUE TITLE
Opencost: Calling hooks inside a processor

### ISSUE THREAD

**Issue by sniok** [headlamp-k8s/plugins#83]
There are some warnings and errors which I think are related to it 

```
configStore.ts:69 Warning: Do not call Hooks inside useEffect(...), useMemo(...), or other built-in Hooks. You can only call Hooks at the top level of your React function. For more information, see https://reactjs.org/link/rules-of-hooks
    at ResourceTableContent (http://localhost:3000/src/components/common/Resource/ResourceTable.tsx:131:5)
```

```
The above error occurred in the <ResourceTableContent> component:

    at ResourceTableContent (http://localhost:3000/src/components/common/Resource/ResourceTable.tsx:131:5)
```

My guess is the issue is with this line https://github.com/headlamp-k8s/plugins/blob/main/opencost/src/index.tsx#L136
where a hook gets called inside a processor (which is not a hook and not a component)

**Comment by sniok** [comment]
Crash is happening only on the react-query branch, which means this is not opencost plugin issue, my bad. Renamed it to only mention the warnings which are still valid
